---
title: "Diagnosing-identification"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Diagnosing-identification}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = F
)
```

## Diagnosing identification of the model

This document covers how to use the function `diagnose_identification` for diagnosing identifiication of the model.

```{r setup}
library(pimbayes)
```


```{r}
ll_cross <- function(data, theta){
  se = theta[1]
  sp = theta[2]
  pi = theta[3:5]
  pi = c(pi, 1-sum(pi))
  eta =  c(se*pi[1]+(1-sp)*pi[3],
           se*pi[2]+(1-sp)*pi[4],
           sp*pi[3]+(1-se)*pi[1],
           (1-se)*pi[2]+sp*pi[4])
  log(dmultinom(data, prob = eta))
}

data_cross <- function(args) {
  theta = args$theta
  n = args$n
  se = theta[1]
  sp = theta[2]
  pi = theta[3:5]
  pi = c(pi, 1-sum(pi))
  eta =  c(se*pi[1]+(1-sp)*pi[3],
           se*pi[2]+(1-sp)*pi[4],
           sp*pi[3]+(1-se)*pi[1],
           (1-se)*pi[2]+sp*pi[4])
  as.vector(rmultinom(1, size = n, prob = eta))
}

jags_code <- "model { 
y[1:4] ~ dmulti(eta[1:4], n)
    eta[1:4] <- c(se*pi[1]+(1-sp)*pi[3],
      se*pi[2]+(1-sp)*pi[4],
      sp*pi[3]+(1-se)*pi[1],
      (1-se)*pi[2]+sp*pi[4])
      pi[1:4] ~ ddirch(c(1,1,1,1))
    se ~ dbeta(25,3)
    sp ~ dbeta(30,1.5)
  }"
data(small_cross)
data = list(y = small_cross, n = sum(small_cross))
diagnose_identification(jags_code, data,
                        c("se","sp","pi[1]","pi[2]","pi[3]"),
                        ll_cross, data_cross)
```
